Repository VertisanPRO/Nexus, pull requests merged in 2022-01, with the labels that each got.

#46 Navbar updates & images removed
  custom/panel_templates/Default/nexus/colors.tpl
  custom/panel_templates/Default/nexus/navbar.tpl
  custom/templates/Nexus/Nexus/components/navbar/dynamic.tpl
  custom/templates/Nexus/Nexus/components/navbar/elegant.tpl
  custom/templates/Nexus/Nexus/images/gigabait.webp
  custom/templates/Nexus/Nexus/images/mubeen.gif
  custom/templates/Nexus/Nexus/images/padow.webp
  custom/templates/Nexus/Nexus/images/sylensky.webp
  modules/Nexus/language/EnglishUK/general.php
  modules/Nexus/language/EnglishUK/navbar.php
  modules/Nexus/language/Russian/general.php
  modules/Nexus/language/Russian/navbar.php
  modules/Nexus/pages/panel/settings.php
Labels: bug

#41 Some grammar fixes
  modules/Nexus/language/EnglishUK/advanced.php
  modules/Nexus/language/EnglishUK/colors.php
  modules/Nexus/language/EnglishUK/connections.php
  modules/Nexus/language/EnglishUK/embed.php
  modules/Nexus/language/EnglishUK/general.php
  modules/Nexus/language/EnglishUK/navbar.php
  modules/Nexus/language/EnglishUK/widgets.php
  modules/Nexus/language/Russian/advanced.php
  modules/Nexus/language/Russian/arc.php
  modules/Nexus/language/Russian/colors.php
  modules/Nexus/language/Russian/connections.php
  modules/Nexus/language/Russian/embed.php
  modules/Nexus/language/Russian/general.php
  modules/Nexus/language/Russian/navbar.php
  modules/Nexus/language/Russian/navigation.php
  modules/Nexus/language/Russian/options.php
  modules/Nexus/language/Russian/widgets.php
Labels: translation

#47 Fixes & additions
  custom/templates/Nexus/index.tpl
  custom/templates/Nexus/resources/categories.tpl
  custom/templates/Nexus/resources/index.tpl
  custom/templates/Nexus/resources/resource.tpl
  custom/templates/Nexus/resources/resource_all_releases.tpl
  custom/templates/Nexus/resources/resource_all_reviews.tpl
  custom/templates/Nexus/resources/resource_all_versions.tpl
  custom/templates/Nexus/rules.tpl
  custom/templates/Nexus/staff.tpl
  custom/templates/Nexus/status.tpl
  custom/templates/Nexus/tebex/category.tpl
  custom/templates/Nexus/tebex/index.tpl
  custom/templates/Nexus/tebex/widgets/latest_purchases.tpl
  custom/templates/Nexus/wiki/index.tpl
  custom/templates/Nexus/wiki/search.tpl
  custom/templates/Nexus/wiki/widgets/search-box.tpl
  custom/templates/Nexus/wiki/widgets/side-menu.tpl
Labels: bug, enhancement
